### ISSUE TITLE
3주차 작업 계획

### ISSUE THREAD

**Issue by datalater** [CodeSoom/project-react-3-datalater#12]
# 프로젝트

## 01 이 앱을 언제 사용하나요?

사용자는 친구와 약속을 정할 때 중간지점을 알고 싶을 때 사용합니다.

## 02 제약 조건은 무엇인가요?

친구의 수를 3명으로 제한합니다.

## 03 구체적인 사례는 무엇인가요?

정자역과 잠실역의 중간지점을 구합니다. 복정역이 나옵니다.

## 04 이번주에 구현할 가치가 있는 기능을 우선 순위대로 작성해주세요.

- [x] 사용자는 출발지점을 두 개 받으면 중간지점을 알 수 있다. #16 
- [x] 사용자는 출발지점과 중간지점을 지도에서 확인할 수 있다. #18 

## 05 그외 필요한 작업을 작성해주세요.

- [x] 잘못된 위치에서 스크립트를 로딩하지 않도록 스크립트 로딩 경로를 절대 경로로 변경하기 #13
- [x] 없는 URL을 요청받을 경우 Not Found 페이지로 리다이렉트 되지 않는 에러 해결하기 #14 
- [x] 중간지점 버튼 추가하기 #15 
- [x] 결과 페이지에 지도 띄우기 #17 

# 진행상황

[Notion Page](https://www.notion.so/jayday/11-d6545950be984a6c835b0c5e5f9c9cdd)

# 회고

[Notion Page](https://www.notion.so/jayday/11-74a0c6e028d94771a6f1de301eebaafb)

**Comment by datalater** [comment]
# 장애

production 환경에서 react router가 제대로 작동하지 않는다.

webpack에서 historyApiFallback을 하면 /index.html로 리다이렉트 되는 기능이 프로덕션에서는 작동하지 않는 것으로 추정된다.
흠 아직까지는 어떻게 디버깅을 해야 할지 모르겠다.

<img width="888" alt="Screen Shot 2021-04-06 at 18 15 03" src="https://user-images.githubusercontent.com/8105528/113688273-19983180-9704-11eb-980c-42dd376a9257.png">

**Comment by datalater** [comment]
갑자기 생각났는데 e2e 테스트를 작성했으면 배포 단계에서 라우팅 오류를 잡아냈을 것이다. e2e 테스트 코드 작성을 고려하자.

**Comment by moonkii** [comment]
GitHub Pages 를 사용하는 경우에는 편법이지만 `404.html` 을 많이 사용해요.
자체적으로 제공해주기 때문이에요.

CI 에서는 그래서 `index.html` 을 `404.html` 로 복사하는 스크립트를 추가해주면 될거에요 ;)

참고: 
- [creating-a-custom-404-page-for-your-github-pages-site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site)

**Comment by datalater** [comment]
> GitHub Pages 를 사용하는 경우에는 편법이지만 `404.html` 을 많이 사용해요.
> 자체적으로 제공해주기 때문이에요.
> 
> CI 에서는 그래서 `index.html` 을 `404.html` 로 복사하는 스크립트를 추가해주면 될거에요 ;)
> 
> 참고:
> 
> * [creating-a-custom-404-page-for-your-github-pages-site](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site)

아하!!! 그렇군요. Github Pages가 자체 제공하는 기능이었군요 ㅎㅎ 감사합니다.

그러면 편법이 아닌 정식으로는 어떻게 해야 할까요?

구글링을 해보니 backend 서버에서 redirect 코드를 집어 넣어서 처리하던데, backend 서버가 없을 경우 대비할 수 없나요?

**Comment by datalater** [comment]
# TODO

출발 주소를 등록할 때 컴포넌트 이름을 PlayerAddress라고 했는데 그냥 UserAddress가 훨씬 나은 것 같다.

나중에 리팩토링하자:
* Player => User

**Comment by datalater** [comment]
# 어떻게 하면 더 나을까

기능이 배포될 때마다 기능에 대한 설명을 `README.md`에 추가하자.

**Comment by moonkii** [comment]
정식으로 할려면 직접 호스팅해야죠 ;)

GitHub 에서는 지원하지 않는걸 가능하게 하려고 하다보니 이렇게 사용할 수 밖에 없어요.

아니면 말씀하신대로 서버가 있으면 서버에서 처리해줄 순 있겠죠?

**Comment by datalater** [comment]
> 정식으로 할려면 직접 호스팅해야죠 ;)
> 
> GitHub 에서는 지원하지 않는걸 가능하게 하려고 하다보니 이렇게 사용할 수 밖에 없어요.
> 
> 아니면 말씀하신대로 서버가 있으면 서버에서 처리해줄 순 있겠죠?

지금으로서는 이게 최선이군요! 감사합니다 ㅎㅎ

**Comment by datalater** [comment]
# 고민

## 정교하지만 개발에 시간이 걸리는 알고리즘 vs 부정확하지만 빠르게 개발할 수 있는 알고리즘

중간지점을 구하는 알고리즘은 좀더 정교하게 짜는 알고리즘이 있고 빠르게 짤 수 있는 알고리즘이 있다. 

일단 지금은 빠르게 짤 수 있는 알고리즘을 빠르게 배포해서 가치를 전달하고, 그 이후에 정교하게 짜는 알고리즘을 개발하자.

**Comment by datalater** [comment]
# Next

* 전체 스타일링
* 추천 장소 클릭하면 해당하는 marker에 인포 윈도우 토글 시키기

**Comment by datalater** [comment]
# 회고

[Notion](https://www.notion.so/jayday/11-74a0c6e028d94771a6f1de301eebaafb)
