### ISSUE TITLE
4주차 작업 계획

### ISSUE THREAD

**Issue by datalater** [CodeSoom/project-react-3-datalater#19]
# 프로젝트

## 01 이 앱을 언제 사용하나요?

사용자는 친구와 약속을 정할 때 중간지점을 알고 싶을 때 사용합니다.

## 02 제약 조건은 무엇인가요?

친구의 수를 3명으로 제한합니다.

## 03 구체적인 사례는 무엇인가요?

정자역과 잠실역의 중간지점을 구합니다. 복정역이 나옵니다.

## 04 이번주에 구현할 가치가 있는 기능을 우선 순위대로 작성해주세요.

- [X] 추천장소를 클릭하면 해당 마커만 지도에 표시된다. #28 
- [X] UI를 개선한다. (어떻게 구체적으로 써야 할지 모르겠다)
- [ ] 중간지점으로 지하철역이 없을 경우 랜드마크를 추천한다. (4주차 이후에 진행 예상)
- [ ] 소요시간이 나온다. (4주차 이후에 진행 예상)

## 05 그외 필요한 작업을 작성해주세요.

- [X] `README.md`에 지난주에 배포된 기능에 대한 스크린샷 추가 #20 
- [X] 리액트 컴포넌트 및 핸들러 함수 최적화 #25 
- [X] [배포 환경에서 응답시간이 10초 이상 걸리는 문제 해결](https://github.com/CodeSoom/project-react-3-datalater/issues/19#issuecomment-820145130) #26
- [X] 장소 등록을 위한 검색 결과는 메모이즈드 컴포넌트로 최적화할 필요가 없으므로 최적화 취소 #27
- [X] 검색 폼 UI를 모던(?)하게 바꾸기 #29 

# 진행상황

[Notion Page](https://www.notion.so/jayday/12-71d28141762b44b9a98d287cf6e86170)

# 회고

**Comment by Kihyun92** [comment]
벌써 마지막 주차네요! 

서비스를 사용해보니 어느정도 의도하신대로 잘 구현하신 것 같아요~

남은 기능도 잘 완료해보시면 좋을 것 같습니다 👍🏼

**Comment by datalater** [comment]
# 장애 발생

## 장애 내용 

첫 페이지 로딩 시간이 14초 걸린다.

![image](https://user-images.githubusercontent.com/8105528/114822511-218b5c00-9dfd-11eb-9a11-f324942ab2d3.png)

## 할 일

왜 이렇게 오래 걸리는지, 어떤 커밋부터 이렇게 된 건지 알아봐야겠다.

**Comment by datalater** [comment]
# 느낀 점

장애 한 번 발생하면 해결하는데 3시간 걸리는 건 흔한 일이다. 따라서 내가 사용하는 기술을 잘 알고 사용해야 한다. 처음에는 원하는 기능만 빠르게 만들고 싶은 생각이 들지만, 차근차근 확실히 학습하고 기술을 사용하는 것이 전체적인 리드타임이 더 짧기 때문이다.

**Comment by Kihyun92** [comment]
트러블 슈팅 과정을 잘 정리해주신 것 같아요. 슬랙 채널을 통해 동료들에게 공유해도 좋을 것 같네요 👍🏼

**Comment by datalater** [comment]
넵 ㅎㅎㅎ

**Comment by datalater** [comment]
# TODO

1. 글로벌 헤더 없애고 "뒤로가기" 버튼 추가하기
2. 모바일 크롬에서 주소 바 때문에 생기는 세로 스크롤 없애기
3. 컴포넌트 역할별로 디렉토리 구분하기
4. 스타일링 코드 깔끔하게 분리하기

**Comment by datalater** [comment]
다시 작업 시작!
